# Generated by Django 6.0.1 on 2026-01-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('в процессе', 'In Progress'), ('в пути', 'In Way'), ('Готов', 'Ready'), ('Ошибка', 'Error')], default='в процессе', max_length=128, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_moment', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('order_attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_theme.user_order')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
