# Generated by Django 6.0.1 on 2026-01-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_theme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_order',
            new_name='UserOrder',
        ),
        migrations.AlterField(
            model_name='bucketitem',
            name='price_in_moment',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
